resource_group_name  = "rg-prod"
location             = "westeurope"
storage_account_name = "prodstorageacctbestrong1"
ai_account_name      = "prodformai1"
app_service_plan_name = "prodbestrongplan1"
function_app_name = "prodbestrongfuncapp1"
ai_sku = "S0"