trigger:
  branches:
    include:
      - main

variables:
  environment: 'prod'

stages:
  - stage: Terraform
    jobs:
    - job: Terraformjob
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'bestrong-arm'
          KeyVaultName: 'newbestrongkeyvault1'
          SecretsFilter: 'TerraformClientId,TerraformTenantId,TerraformClientSecret,TerraformSubscriptionId'
          RunAsPreJob: true
      - script: |
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(TerraformClientId)"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(TerraformTenantId)"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$(TerraformClientSecret)"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(TerraformSubscriptionId)"
        displayName: 'Set Terraform environment variables'

      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '1.6.6' 


      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendAzureRmUseEntraIdForAuthentication: false
          backendServiceArm: 'bestrong-arm'
          backendAzureRmStorageAccountName: 'tfstatestoragebestrong1'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'tfstate'


      - script: |
          terraform workspace select $(environment) || terraform workspace new $(environment)
        displayName: 'Select or create terraform workspace'
          
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-var-file="env/$(environment)/terraform.tfvars"'
          environmentServiceNameAzureRM: 'bestrong-arm'
        displayName: 'Terraform plan'
      
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '-var-file="env/$(environment)/terraform.tfvars"'
          environmentServiceNameAzureRM: 'bestrong-arm'
        displayName: 'Terraform apply'