resource_group_name  = "rg-dev"
location             = "westeurope"
storage_account_name = "devstorageacctbestrong1"
ai_account_name      = "devformai1"
app_service_plan_name = "devbestrongplan1"
function_app_name = "devbestrongfuncapp1"
ai_sku = "F0"